int _putchar(char c);
int print_alphabet();
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int a);
int print_last_digit(int c);
void jack_bauer(void);
void time_table(void);
